POST http://localhost:3000/register
Content-Type: application/json

{
"username": "srikanth_sura",
"name": "Srikanth Sura",
"password": "srikanth@123",
"gender": "male",
"location": "India"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "srikanth_sura",
    "password" : "srikanth@456"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "srikanth_sura",
  "oldPassword": "srikanth@456",
  "newPassword": "srikanth@123"
}